### PR TITLE
Issue fixes

### LINKED ISSUE #23: Fix responsiveness in mobile view
For reference: 
SL

### PR DESCRIPTION
**Pull request by crs26**
#23 
#61 
#62 
#63

### CODE REVIEW

**Comment by crs26** [comment]
image

**Review by Pseudoman21 — APPROVED** [review]
Awesome picx!

**Comment by harveyjavier** [comment]
> #23
> #61
> #62
> #63

@crs26 next time lagyan mo chan ng _Closes_ or _Resolves_ keyword para ma reference ang issue and at the same time ma close na din

**Comment by harveyjavier** [comment]
Example `closes #23`

**Comment by Pseudoman21** [comment]
Ay iyu palan @crs26, thank you po Kuya @harveyjavier ^^

**Comment by crs26** [comment]
Sige po sir @harveyjavier noted po

**Pull request merged**
