### PR TITLE
Add register button in landing page

### PR DESCRIPTION
**Pull request by Pseudoman21**
Add REGISTER NOW button in login page of SparkLearn to redirect in SparkEarn register page.

### CODE REVIEW

**Comment by ricoz** [comment]
Please upload screenshot @Pseudoman21

**Comment by Pseudoman21** [comment]
Ay opo Sir. Ito po ^_^ 
image

**Review by ricoz — CHANGES_REQUESTED** [review]
Add space between login and register buttons in mobile and make the corner radius uniform

**Comment by Pseudoman21** [comment]
On it po Sir.

**Comment by Pseudoman21** [comment]
Changed to both lowercase, add space between buttons and make border radius uniform.
image

**Review by ricoz — APPROVED** [review]
👍

**Review by EJBarba — APPROVED** [review]
👌

**Review by harveyjavier — APPROVED** [review]
Signed up!

**Comment by ricoz** [comment]
Test Slack integration

**Pull request merged**
