### PR TITLE
New UI Application - Homepage Section

### PR DESCRIPTION
**Pull request by Pseudoman21**

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
Initialized!

**Review by swengr-janan — APPROVED** [review]
Newed!

**Comment by harveyjavier** [comment]
Screenshots jeypz

**Comment by Pseudoman21** [comment]
> Screenshots jeypz
Ay opo Kuya ^^

Landing page
image

Login page:
image

**Comment by harveyjavier** [comment]
Crispy! Mobile responsive naman ini Jeypz?

**Comment by Pseudoman21** [comment]
> Crispy! Mobile responsive naman ini Jeypz?

Yes po Kuya ^^
image

**Review by harveyjavier — CHANGES_REQUESTED** [review]
Screenshot 2021-07-27 092711

center ta ining buttons pag naka mobile view. i-media query hardkud nlng nindo or via `col` ni bootstrap

**Comment by Pseudoman21** [comment]
> center ta ining buttons pag naka mobile view. i-media query hardkud nlng nindo or via `col` ni bootstrap

Ay tinks po Kuya, fix ko lang po si mailjet tapos yan po sa contact ^^

**Comment by harveyjavier** [comment]
also better ma-minimize sya pag naka mobile view, yung may scrollbar. as much as possible, ma avoid si scrollbar

**Comment by harveyjavier** [comment]
oki jeypz ^^

**Comment by Pseudoman21** [comment]
> also better ma-minimize sya pag naka mobile view, yung may scrollbar. as much as possible, ma avoid si scrollbar

Ay sigi po Kuya, yaon po siya kay miljet ^^

**Comment by Pseudoman21** [comment]
Fixed po Kuya @harveyjavier 
image

**Comment by harveyjavier** [comment]
Noice Jeypz! Apprubing

**Review by harveyjavier — APPROVED** [review]
LGTH!

**Comment by Pseudoman21** [comment]
> Noice Jeypz! Apprubing

Tinks po Kuya ^^

**Pull request merged**
